FROM alpine

RUN adduser -D -u 1000 app \
 && mkdir /app \
 && chown app:app /app \
 && apk add --no-cache \
    py3-pip \
 && pip3 install pytest requests

USER app

WORKDIR /app
COPY --chown=app:app . .

CMD ["/usr/bin/pytest", "test/acceptance.py"]
