@Library('jenkins-pipeline-library-v2') _

pythonPipeline(
    project: 'example-docker-flask-hudson',
    gateNotificationEmails: 'AgileTeamDeploymentAutomation@icims.com',
    associatedProduct: 'YAP Example Projects',
    notifySlackChannel: 'devops_coe_notices',
    regions: 'us-east-1,ca-central-1,eu-central-1,us-west-2,eu-west-1',
    track: 'standard-isv',
    teamName: 'svcAgileTeamDeplAuto',
    buildSchedule: [
        frequency: 'daily',
        branch: 'master'
    ]
)
